package com.phms.mapper;

import com.phms.pojo.PetDaily;
import com.phms.pojo.PetDailyExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface PetDailyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pet_daily
     *
     * @mbg.generated Mon Apr 06 17:03:33 CST 
     */
    long countByExample(PetDailyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pet_daily
     *
     * @mbg.generated Mon Apr 06 17:03:33 CST 
     */
    int deleteByExample(PetDailyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pet_daily
     *
     * @mbg.generated Mon Apr 06 17:03:33 CST 
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pet_daily
     *
     * @mbg.generated Mon Apr 06 17:03:33 CST 
     */
    int insert(PetDaily record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pet_daily
     *
     * @mbg.generated Mon Apr 06 17:03:33 CST 
     */
    int insertSelective(PetDaily record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pet_daily
     *
     * @mbg.generated Mon Apr 06 17:03:33 CST 
     */
    List<PetDaily> selectByExample(PetDailyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pet_daily
     *
     * @mbg.generated Mon Apr 06 17:03:33 CST 
     */
    PetDaily selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pet_daily
     *
     * @mbg.generated Mon Apr 06 17:03:33 CST 
     */
    int updateByExampleSelective(@Param("record") PetDaily record, @Param("example") PetDailyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pet_daily
     *
     * @mbg.generated Mon Apr 06 17:03:33 CST 
     */
    int updateByExample(@Param("record") PetDaily record, @Param("example") PetDailyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pet_daily
     *
     * @mbg.generated Mon Apr 06 17:03:33 CST 
     */
    int updateByPrimaryKeySelective(PetDaily record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pet_daily
     *
     * @mbg.generated Mon Apr 06 17:03:33 CST 
     */
    int updateByPrimaryKey(PetDaily record);

    List<PetDaily> getAllByLimit(PetDaily po);

    int countAllByLimit(PetDaily po);
}